// <auto-generated />
using System;
using ApplyVault.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplyVault.Api.Migrations
{
    [DbContext(typeof(ApplyVaultDbContext))]
    [Migration("20260404045319_AddGmailMailSync")]
    partial class AddGmailMailSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplyVault.Api.Data.AppUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SupabaseUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.CalendarEventLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConnectedAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalEventUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScrapeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAccountId", "ExternalEventId")
                        .IsUnique();

                    b.HasIndex("ScrapeResultId", "ConnectedAccountId")
                        .IsUnique();

                    b.ToTable("CalendarEventLinks");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ConnectedAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastHistoryId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyncStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("ConnectedAccounts");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewEventEntity", b =>
                {
                    b.Property<Guid>("ScrapeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScrapeResultId");

                    b.ToTable("InterviewEvents");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ScrapeResultContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScrapeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeResultId");

                    b.ToTable("ScrapeResultContacts");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ScrapeResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CaptureOverallConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("CaptureReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("not_required");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CompanyNameConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("CompanyNameOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyNameReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectedPageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiringManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("InterviewDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRejected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("JobDescriptionConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("JobDescriptionOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDescriptionReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("JobTitleConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("JobTitleOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitleReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastStatusEmailFrom")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset?>("LastStatusEmailReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastStatusEmailSubject")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("LastStatusKind")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LastStatusSource")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("LastStatusUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LocationConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("LocationOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceHostname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TextLength")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ScrapeResults");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.CalendarEventLinkEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.ConnectedAccountEntity", "ConnectedAccount")
                        .WithMany("CalendarEventLinks")
                        .HasForeignKey("ConnectedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplyVault.Api.Data.ScrapeResultEntity", "ScrapeResult")
                        .WithMany("CalendarEventLinks")
                        .HasForeignKey("ScrapeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectedAccount");

                    b.Navigation("ScrapeResult");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ConnectedAccountEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.AppUserEntity", "User")
                        .WithMany("ConnectedAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewEventEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.ScrapeResultEntity", "ScrapeResult")
                        .WithOne("InterviewEvent")
                        .HasForeignKey("ApplyVault.Api.Data.InterviewEventEntity", "ScrapeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapeResult");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ScrapeResultContactEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.ScrapeResultEntity", null)
                        .WithMany("HiringManagerContacts")
                        .HasForeignKey("ScrapeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ScrapeResultEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.AppUserEntity", "User")
                        .WithMany("ScrapeResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.AppUserEntity", b =>
                {
                    b.Navigation("ConnectedAccounts");

                    b.Navigation("ScrapeResults");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ConnectedAccountEntity", b =>
                {
                    b.Navigation("CalendarEventLinks");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ScrapeResultEntity", b =>
                {
                    b.Navigation("CalendarEventLinks");

                    b.Navigation("HiringManagerContacts");

                    b.Navigation("InterviewEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
