// <auto-generated />
using System;
using ApplyVault.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplyVault.Api.Migrations
{
    [DbContext(typeof(ApplyVaultDbContext))]
    partial class ApplyVaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplyVault.Api.Data.AppUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SupabaseUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.CalendarEventLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConnectedAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalEventUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScrapeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAccountId", "ExternalEventId")
                        .IsUnique();

                    b.HasIndex("ScrapeResultId", "ConnectedAccountId")
                        .IsUnique();

                    b.ToTable("CalendarEventLinks");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ConnectedAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastHistoryId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyncStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("ConnectedAccounts");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewEventEntity", b =>
                {
                    b.Property<Guid>("ScrapeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScrapeResultId");

                    b.ToTable("InterviewEvents");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepAnswerRetryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateTurnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoachingFeedbackJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComparisonJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InterviewerTurnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalAnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalAssessmentJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevisedAnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevisedAssessmentJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CandidateTurnId")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.ToTable("InterviewPrepAnswerRetries", (string)null);
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepCompetencyCoverageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("CompetencyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CoverageState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("int");

                    b.Property<string>("LastProgressClass")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CompetencyId")
                        .IsUnique();

                    b.ToTable("InterviewPrepCompetencyCoverages", (string)null);
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepEvidenceItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CandidateTurnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CompetencyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EvidenceQuote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Polarity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CompetencyId");

                    b.ToTable("InterviewPrepEvidenceItems", (string)null);
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepQuestionAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssessmentJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssessmentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("CandidateTurnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompetencyId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IntentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("InterviewerTurnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProgressClass")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetEvidenceKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CandidateTurnId");

                    b.ToTable("InterviewPrepQuestionAttempts", (string)null);
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepStudyBriefEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CvDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CvFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FocusNoteSnapshot")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("ScrapeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UsedAiFallback")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasJobBound")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeResultId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_InterviewPrepStudyBriefs_UserId_CvOnly")
                        .HasFilter("[ScrapeResultId] IS NULL");

                    b.HasIndex("UserId", "GeneratedAt")
                        .IsDescending(false, true);

                    b.HasIndex("UserId", "ScrapeResultId")
                        .IsUnique()
                        .HasFilter("[ScrapeResultId] IS NOT NULL");

                    b.ToTable("InterviewPrepStudyBriefs", (string)null);
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BriefJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CandidateReportJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatalogVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ConcurrencyStamp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConversationSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CvDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CvSnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("JobSnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PanelDebriefJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PlanJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PreparedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RuntimeStateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ScrapeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StageAssessmentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeResultId");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("UserId", "UpdatedAt")
                        .IsDescending(false, true);

                    b.ToTable("InterviewPrepSessions", (string)null);
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepStageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlanJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StageType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("InterviewPrepStages", (string)null);
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepTurnEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClientTurnId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CompetencyTag")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IntentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("QuestionSignature")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetEvidenceKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("SessionId", "ClientTurnId")
                        .IsUnique()
                        .HasFilter("[ClientTurnId] IS NOT NULL");

                    b.HasIndex("SessionId", "QuestionSignature");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("InterviewPrepTurns", (string)null);
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ScrapeResultContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScrapeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeResultId");

                    b.ToTable("ScrapeResultContacts");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ScrapeResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CaptureOverallConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("CaptureReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("not_required");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CompanyNameConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("CompanyNameOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyNameReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectedPageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiringManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("InterviewDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRejected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("JobDescriptionConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("JobDescriptionOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDescriptionReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("JobTitleConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("JobTitleOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitleReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastStatusEmailFrom")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset?>("LastStatusEmailReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastStatusEmailSubject")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("LastStatusKind")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LastStatusSource")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("LastStatusUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LocationConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("LocationOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceHostname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TextLength")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ScrapeResults");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.UserCvDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("OriginalFileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfilePhotoContentType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProfilePhotoStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("StructuredImportedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCvDocuments");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.UserCvEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BulletsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateRange")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FieldsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("SourceSummaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SourceSummaryId");

                    b.HasIndex("SectionId", "SortOrder");

                    b.ToTable("UserCvEntries");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.UserCvProjectSummaryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CvBullets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("ExternalRepoId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HtmlUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PrimaryLanguage")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Topics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExternalRepoId")
                        .IsUnique();

                    b.ToTable("UserCvProjectSummaries");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.UserCvSectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("UserCvDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserCvDocumentId", "SortOrder");

                    b.ToTable("UserCvSections");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.CalendarEventLinkEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.ConnectedAccountEntity", "ConnectedAccount")
                        .WithMany("CalendarEventLinks")
                        .HasForeignKey("ConnectedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplyVault.Api.Data.ScrapeResultEntity", "ScrapeResult")
                        .WithMany("CalendarEventLinks")
                        .HasForeignKey("ScrapeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectedAccount");

                    b.Navigation("ScrapeResult");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ConnectedAccountEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.AppUserEntity", "User")
                        .WithMany("ConnectedAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewEventEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.ScrapeResultEntity", "ScrapeResult")
                        .WithOne("InterviewEvent")
                        .HasForeignKey("ApplyVault.Api.Data.InterviewEventEntity", "ScrapeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapeResult");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepAnswerRetryEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.InterviewPrepSessionEntity", "Session")
                        .WithMany("AnswerRetries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepCompetencyCoverageEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.InterviewPrepSessionEntity", "Session")
                        .WithMany("CompetencyCoverages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepEvidenceItemEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.InterviewPrepSessionEntity", "Session")
                        .WithMany("EvidenceItems")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepQuestionAttemptEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.InterviewPrepSessionEntity", "Session")
                        .WithMany("QuestionAttempts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepSessionEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.ScrapeResultEntity", null)
                        .WithMany()
                        .HasForeignKey("ScrapeResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApplyVault.Api.Data.AppUserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepStudyBriefEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.ScrapeResultEntity", null)
                        .WithMany()
                        .HasForeignKey("ScrapeResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApplyVault.Api.Data.AppUserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepStageEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.InterviewPrepSessionEntity", "Session")
                        .WithMany("Stages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepTurnEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.InterviewPrepSessionEntity", "Session")
                        .WithMany("Turns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplyVault.Api.Data.InterviewPrepStageEntity", "Stage")
                        .WithMany("Turns")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ScrapeResultContactEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.ScrapeResultEntity", null)
                        .WithMany("HiringManagerContacts")
                        .HasForeignKey("ScrapeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ScrapeResultEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.AppUserEntity", "User")
                        .WithMany("ScrapeResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.UserCvDocumentEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.AppUserEntity", "User")
                        .WithOne("CvDocument")
                        .HasForeignKey("ApplyVault.Api.Data.UserCvDocumentEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.UserCvEntryEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.UserCvSectionEntity", "Section")
                        .WithMany("Entries")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplyVault.Api.Data.UserCvProjectSummaryEntity", "SourceSummary")
                        .WithMany()
                        .HasForeignKey("SourceSummaryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Section");

                    b.Navigation("SourceSummary");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.UserCvProjectSummaryEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.AppUserEntity", "User")
                        .WithMany("CvProjectSummaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.UserCvSectionEntity", b =>
                {
                    b.HasOne("ApplyVault.Api.Data.UserCvDocumentEntity", "Document")
                        .WithMany("Sections")
                        .HasForeignKey("UserCvDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.AppUserEntity", b =>
                {
                    b.Navigation("ConnectedAccounts");

                    b.Navigation("CvDocument");

                    b.Navigation("CvProjectSummaries");

                    b.Navigation("ScrapeResults");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ConnectedAccountEntity", b =>
                {
                    b.Navigation("CalendarEventLinks");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepSessionEntity", b =>
                {
                    b.Navigation("AnswerRetries");

                    b.Navigation("CompetencyCoverages");

                    b.Navigation("EvidenceItems");

                    b.Navigation("QuestionAttempts");

                    b.Navigation("Stages");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.InterviewPrepStageEntity", b =>
                {
                    b.Navigation("Turns");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.ScrapeResultEntity", b =>
                {
                    b.Navigation("CalendarEventLinks");

                    b.Navigation("HiringManagerContacts");

                    b.Navigation("InterviewEvent");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.UserCvDocumentEntity", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ApplyVault.Api.Data.UserCvSectionEntity", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
